In [1]:
import numpy as np

In [5]:
A=np.ones((3,4),dtype=int)
A

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
A=np.zeros((5,5),dtype=bool)
A

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
empty=np.empty((2,2),dtype=int)
empty

array([[  912553163,   712393111],
       [-1490443010, -1942943031]])

In [8]:
A=np.ones((5,5),dtype=bool)
A

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [32]:
A=np.arange(1,51,2)
A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [33]:
B=A.reshape(5,5)
B

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [24]:
C=B.ravel()

In [26]:
C[2]=555

In [27]:
C

array([  1,   3, 555,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49])

In [28]:
B

array([[  1,   3, 555,   7,   9],
       [ 11,  13,  15,  17,  19],
       [ 21,  23,  25,  27,  29],
       [ 31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49]])

In [34]:
D=B.flatten()
D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [35]:
D[2]=556
D

array([  1,   3, 556,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49])

In [36]:
B

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [38]:
C=B.transpose()
C

array([[ 1, 11, 21, 31, 41],
       [ 3, 13, 23, 33, 43],
       [ 5, 15, 25, 35, 45],
       [ 7, 17, 27, 37, 47],
       [ 9, 19, 29, 39, 49]])

In [43]:
B@C@B@C

array([[  2836125,   8242375,  13648625,  19054875,  24461125],
       [  8242375,  23961125,  39679875,  55398625,  71117375],
       [ 13648625,  39679875,  65711125,  91742375, 117773625],
       [ 19054875,  55398625,  91742375, 128086125, 164429875],
       [ 24461125,  71117375, 117773625, 164429875, 211086125]])